services:
  postgres:
    image: postgres:15-alpine
    container_name: super-salary-db
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpass
      POSTGRES_DB: super_salary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
